### ISSUE TITLE
Exception raised when running with unescaped cmd

### ISSUE THREAD

**Issue by pwwang** [kamermans/command#1]
``` php
$cmd = kamermans\Command\Command::factory(
    'bedtools intersect -sorted -loj -wa -wb -a \'/z/yun/chip-ref/data/hg19-prom.bin50\' -b <(awk \'{print $1"\t"$2"\t"$3"\t"$4"\t"$5}\' \'/z/yun/chip-ref/data//Cebpb/ALL/clusters/chipseq.bed\')',
    true
);
$logger->addInfo(strval($cmd));
$cmd->run();
```

The cmd printed:

``` bash
$ bedtools intersect -sorted -loj -wa -wb -a '/z/yun/chip-ref/data/hg19-prom.bin50' -b <(awk '{print $1"\t"$2"\t"$3"\t"$4"\t"$5}' '/z/yun/chip-ref/data//Cebpb/ALL/clusters/chipseq.bed') |head
chr1    10100   10149   .   -1  -1  .   -1
chr1    10150   10199   chr1    10149   10413   Cebpb   331
chr1    10200   10249   chr1    10149   10413   Cebpb   331
chr1    10250   10299   chr1    10149   10413   Cebpb   331
chr1    10300   10330   chr1    10149   10413   Cebpb   331
chr1    10345   10394   chr1    10149   10413   Cebpb   331
chr1    10395   10444   chr1    10149   10413   Cebpb   331
```

But when running the php script, an exception raised:

``` bash
[2015-11-24 11:43:58] scoreRegions.INFO: bedtools intersect -sorted -loj -wa -wb -a '/z/yun/chip-ref/data/hg19-prom.bin50' -b <(awk '{print $1"\t"$2"\t"$3"\t"$4"\t"$5}' '/z/yun/chip-ref/data//Cebpb/ALL/clusters/chipseq.bed') [] []
PHP Fatal error:  Uncaught exception 'kamermans\Command\CommandException' with message 'Command failed 'bedtools intersect -sorted -loj -wa -wb -a '/z/yun/chip-ref/data/hg19-prom.bin50' -b <(awk '{print $1"\t"$2"\t"$3"\t"$4"\t"$5}' '/z/yun/chip-ref/data//Cebpb/ALL/clusters/chipseq.bed')':
sh: 1: Syntax error: "(" unexpected' in /z/yun/chip-ref/tools/vendor/kamermans/command/src/Command.php:210
Stack trace:
#0 /z/yun/chip-ref/tools/scoreRegions.php(63): kamermans\Command\Command->run()
#1 {main}
  thrown in /z/yun/chip-ref/tools/vendor/kamermans/command/src/Command.php on line 210
```

Any ideas?

**Comment by pwwang** [comment]
The other simple example is like:

``` php
$cmd = kamermans\Command\Command::factory(
    'head -10 <(awk \'{print $1"\t"$2"\t"$3"\t"$4"\t"$5}\' \'/z/yun/chip-ref/data//Cebpb/ALL/clusters/chipseq.bed\')',
    true
);
$logger->addInfo(strval($cmd));
$cmd->run();
```

The printed out command could run normally:

``` bash
$ head -10 <(awk '{print $1"\t"$2"\t"$3"\t"$4"\t"$5}' '/z/yun/chip-ref/data//Cebpb/ALL/clusters/chipseq.bed')
chr1    10149   10413   Cebpb   331
chr1    713967  714231  Cebpb   153
chr1    714976  715276  Cebpb   212
chr1    748139  748439  Cebpb   469
chr1    852062  852326  Cebpb   219
chr1    855552  855816  Cebpb   359
chr1    919972  920248  Cebpb   213
chr1    926221  926497  Cebpb   232
chr1    936161  936425  Cebpb   1000
chr1    942024  942248  Cebpb   396
```

But with the php script, exception raised:

``` bash
[2015-11-24 11:52:18] scoreRegions.INFO: head -10 <(awk '{print $1"\t"$2"\t"$3"\t"$4"\t"$5}' '/z/yun/chip-ref/data//Cebpb/ALL/clusters/chipseq.bed') [] []
PHP Fatal error:  Uncaught exception 'kamermans\Command\CommandException' with message 'Command failed 'head -10 <(awk '{print $1"\t"$2"\t"$3"\t"$4"\t"$5}' '/z/yun/chip-ref/data//Cebpb/ALL/clusters/chipseq.bed')':
sh: 1: Syntax error: "(" unexpected' in /z/yun/chip-ref/tools/vendor/kamermans/command/src/Command.php:210
Stack trace:
#0 /z/yun/chip-ref/tools/scoreRegions.php(63): kamermans\Command\Command->run()
#1 {main}
  thrown in /z/yun/chip-ref/tools/vendor/kamermans/command/src/Command.php on line 210

```

**Comment by pwwang** [comment]
Sorry, my bad. `proc_open` and relatives use `sh` instead of `bash`.
So when I use `bash -c "$cmd"`, everything runs well.

**Comment by kamermans** [comment]
Sorry for the delay, I'm glad you discovered that it was bash that was required.
